[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[functions."analyze"]
  # Disable caching for the analyze function
  cache-control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200